name = "foodleap-web"
main = ".open-next/worker.js"
compatibility_date = "2025-08-21"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
API_MAIN_URL = "https://foodleap-api.victorlima124tt.workers.dev"
SEARCH_SERVICE_URL = "https://foodleap-search.victorlima124tt.workers.dev"

[observability.logs]
enabled = true
