export const DIET_QUESTIONS = [
  { id: 1, block: 'A' as const, key: 'goal', question: 'O que você quer conquistar com a sua alimentação agora?', description: 'Seu objetivo é nossa bússola. Equilibramos calorias e nutrientes para que o plano trabalhe a seu favor.', type: 'single_choice' as const, options: ['emagrecer','ganhar_massa','manter_saudavel','energia','aprender_cozinhar'], required: true },
  { id: 2, block: 'A' as const, key: 'activity_level', question: 'Como é a sua rotina de movimento durante a semana?', description: 'Seu nível de atividade nos ajuda a calcular suas necessidades energéticas e porções que sustentam seu dia.', type: 'single_choice' as const, options: ['sedentario','leve','moderado','intenso'], required: true },
  { id: 3, block: 'A' as const, key: 'restrictions', question: 'Você segue alguma restrição alimentar ou estilo alimentar?', description: 'Garantimos apenas receitas compatíveis com você. Excluímos o que não faz sentido para seu estilo de vida.', type: 'multi_choice' as const, options: ['nenhuma','vegetariano','vegano','sem_lactose','sem_gluten','low_carb','alergia'], required: true },
  { id: 4, block: 'A' as const, key: 'health_conditions', question: 'Existe alguma condição de saúde que gostaria que considerássemos com carinho?', description: 'Não substituímos acompanhamento médico, mas adaptamos sódio, açúcar e fibras para receitas mais leves e seguras.', type: 'multi_choice' as const, options: ['nenhuma','diabetes','hipertensao','colesterol_alto','intestino_sensivel','sop'], required: false },
  { id: 5, block: 'A' as const, key: 'skill_level', question: 'Qual é a sua intimidade com a cozinha hoje?', description: 'Evitamos frustrações. Se está começando, priorizamos pratos simples; se já cozinha bem, trazemos técnicas novas.', type: 'single_choice' as const, options: ['iniciante','intermediario','avancado'], required: true },
  { id: 6, block: 'B' as const, key: 'routine_weekday', question: 'Como é a sua rotina de segunda a sexta?', description: 'Sua rotina define o formato ideal: marmitas práticas, refeições em 15 minutos ou pratos mais elaborados.', type: 'single_choice' as const, options: ['correria','hibrido','home','irregular'], required: true },
  { id: 7, block: 'B' as const, key: 'routine_weekend', question: 'E como você gosta de viver o fim de semana?', description: 'O fim de semana muda tudo. Entendemos se quer praticidade, tempo para cozinhar ou receber quem ama.', type: 'single_choice' as const, options: ['praticidade','mais_tempo','receber','como_fora'], required: true },
  { id: 8, block: 'B' as const, key: 'time_available', question: 'Quanto tempo você gostaria de dedicar a cada refeição?', description: 'Respeitamos seu tempo de verdade. Filtramos receitas que cabem na sua agenda sem estresse.', type: 'single_choice' as const, options: ['15min','30min','45min','60min'], required: true },
  { id: 9, block: 'B' as const, key: 'cook_frequency', question: 'Com que frequência você quer cozinhar na semana?', description: 'Definimos a melhor estratégia: comida fresca todo dia, marmitas 2–3 vezes ou tudo em um dia.', type: 'single_choice' as const, options: ['todo_dia','2_3x','1x','decidir_semana'], required: true },
  { id: 10, block: 'B' as const, key: 'budget', question: 'Qual é o seu orçamento semanal para o mercado?', description: 'Ajustamos receitas e lista de compras para caber no seu bolso, com trocas inteligentes sem perder sabor.', type: 'single_choice' as const, options: ['economico','medio','confortavel','tanto_faz'], required: false },
  { id: 11, block: 'C' as const, key: 'favorite_protein', question: 'Quais proteínas mais te dão prazer? Escolha até 3 favoritas.', description: 'Suas favoritas serão as estrelas do cardápio. Garantimos variedade sem repetir o que você não gosta.', type: 'multi_choice' as const, options: ['frango','carne','porco','peixe_branco','salmao_atum','ovo','grao_lentilha','tofu_soja'], required: true },
  { id: 12, block: 'C' as const, key: 'carbs', question: 'Quais carboidratos e acompanhamentos você mais curte?', description: 'Mapeamos seus acompanhamentos preferidos para pratos que realmente saciam e combinam com seu objetivo.', type: 'multi_choice' as const, options: ['arroz','macarrao','pao_tapioca','batata_mandioca','cuscuz','quinoa_aveia','evito_carb_noite'], required: true },
  { id: 13, block: 'C' as const, key: 'hated_ingredients', question: 'Tem algum ingrediente que você prefere evitar?', description: 'Conte sem medo. Nunca sugeriremos receitas com o que você não tolera. Seu cardápio, suas regras.', type: 'multi_choice' as const, options: ['coentro','pimentao','cebola','berinjela','cogumelos','figado','outro'], required: false },
  { id: 14, block: 'C' as const, key: 'flavor', question: 'Qual perfil de sabor mais te conquista?', description: 'Seu paladar guia nossos temperos: do comfort food caseiro ao frescor mediterrâneo, sem enjoar.', type: 'single_choice' as const, options: ['caseirinho','picante','agridoce','mediterraneo','cremoso'], required: false },
  { id: 15, block: 'C' as const, key: 'hardest_meal', question: 'Qual refeição é o seu maior desafio hoje?', description: 'Daremos atenção extra onde você mais tropeça, com ideias práticas que tiram o peso da decisão.', type: 'single_choice' as const, options: ['cafe','almoco','jantar','lanches','todas'], required: true },
] as const;

export type DietQuestion = typeof DIET_QUESTIONS[number];
